### PR TITLE
Fixes #14 "Hashids::InputError: unable to unhash"

### LINKED ISSUE #14: Hashids::InputError: unable to unhash
Hey,

Trying to see if I can drop this beautiful gem on my project without making too many (or any if possible) changes to it.

At first look, things seemed to be working immediately after adding the gem with zero change.

Only when running my tests I get to a point where this error appears:

```ruby
Hashids::InputError: unable to unhash
```

This happens when I try an `update` operation on a controller that operates on a special case model. Not sure it is related though, but its the only obvious difference between this failing test and other passing tests.

It is a `PeopleController` that updates a `User` model.

The error of course originates from the `hashids` gem, specifically from [this line][1], but to my understanding it is simply getting an invalid input.

Any thought as to why this happens and maybe a fix?

EDIT:
~~The immediate suspect is [this line with table_name][2]~~ (seems not...)

[1]: https://github.com/peterhellberg/hashids.rb/blob/a8c3b9cf53468bce4cf61a50699f063ea0fe064b/lib/hashids.rb#L184
[2]: https://github.com/jcypret/hashid-rails/blob/master/lib/hashid/rails.rb#L41

### PR DESCRIPTION
**Pull request by jrasanen**
Fixes issue #14. When array is casted into string and tried to decode into hashid.

### CODE REVIEW

**Comment by DannyBen** [comment]
Hey - any reason not to merge this? I would love to go back to using the canonical gem rather than the fork.

**Comment by DannyBen** [comment]
Many thanks.

**Comment by jcypret** [comment]
@DannyBen Can you give the master branch another try? I refactored some of the code to allow multiple ids to be passed in for decoding. If everything's good, I'll push a new version of the gem :+1:

**Comment by DannyBen** [comment]
Done.

Using `gem 'hashid-rails' , github: 'jcypret/hashid-rails'`

Initial test is a no go. One of my tests fail, raising `ActiveRecord::RecordNotFound` instead of generating a form error.

**Pull request merged**
